# Swagger开启
swagger.enable: true
spring:
  #JPA配置
  jpa:
    database: mysql
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  #    hibernate:
  #      ddl-auto: none
  # 数据库配置
  datasource:
    # ---------------基本链接信息---------------------------
    url: jdbc:mysql://47.103.155.11:3306/blog_2021?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    #driver-class-name: com.mysql.jdbc.Driver
    #platform: mysql
    #type: com.alibaba.druid.pool.DruidDataSource
    # -----------------初始化大小，最小，最大----------------------------
    initialSize: 4
    minIdle: 4
    maxActive: 32
    #是否在自动回收超时连接的时候打印连接的超时错误
    logAbandoned: true
    #是否自动回收超时连接
    removeAbandoned: true
    #超时时间(以秒数为单位)
    removeAbandonedTimeout: 60
    # 配置获取连接等待超时的时间(以毫秒为单位)
    maxWait: 1000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 6000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 'OK'
    testWhileIdle: true
    testOnBorrow: false
    test-on-Return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000

  application:
    name: seata

server:
  port: 18008

seata:
  enabled: true
  enable-auto-data-source-proxy: true #代理数据源
  tx-service-group: my_test_tx_group #要与config.txt中的一致
  registry:
    type: nacos #注册类型
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      namespace: prod
  config:
    type: nacos # 配置中心类型
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      namespace: prod
  service:
    vgroup-mapping:
      my_test_tx_group: default # 默认值，如果在使用事务注解时不指定，采用该默认值
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false
