spring:
  cloud:
    # MQ默认Binder
    stream:
      defaultBinder: rabbit
#################################  rabbitmq 配置  ##############################################################
spring.cloud.stream.bindings:
  customize_output:
    destination: CUSTOMIZE_TOPIC
    content-type: application/json
    group: CUSTOMIZE_TOPIC


  data:
    mongodb:
      authentication-database: hamsv4_developer
      database: hamsv4_developer
      host: 127.0.0.1
      password:
      port: 27017
      username: